apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "exporter-kube-etcd.name" . }}
    component: kube-etcd
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "exporter-kube-etcd.fullname" . }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 4001
      protocol: TCP
      targetPort: 4001
  selector:
    k8s-app: etcd-server
  type: ClusterIP
