apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "exporter-kube-controller-manager.name" . }}
    component: kube-controller-manager
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "exporter-kube-controller-manager.fullname" . }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10252
      protocol: TCP
      targetPort: 10252
  selector:
    k8s-app: kube-controller-manager
  type: ClusterIP
